env:
  dummy: 1
  Q: [100, 100]
  R: [0.1, 0.1]
  P: [100, 100]

optimizer:
  H : 60 # horizon
  Hm : 30 # somewhere in the middle of the horizon
  u_min : [-0.1, -0.1] # Minimum control input
  u_max : [0.1, 0.1]
  x_min : [-200, -200] # Minimum state value
  x_max : [200, 200]
  linear_solver : 'ma57' #
  oracle:
    max_sqp_iter: 10
    tol_nlp: 1.0e-6
  SEMPC:
    max_sqp_iter: 10
    tol_nlp: 1.0e-6 
  Tf: 0.9  # sampling time = Tf/H
  order: 1
  x_dim: 2
  u_dim: 2
  dt: 0.015 # 0.010
  w: 100

tube:
  K: -0.5
  type: 'sub-Gaussian' # 'Gaussian' # 'robust' # 'sub-Gaussian'
  tightening: 0.0
  robust_approach: 'polygon'

algo:
  objective: "GO" 
  strategy: "graph" 
  type: "MPC_V0"

experiment:
  name: "MPC" # name for different type of MPC implementations, for e.g., robust_MPC
  generate_regret_plot : False
  folder: "17-11-2023"